### ISSUE TITLE
Invencibility, music doesn't loop

### ISSUE THREAD

**Issue by Macck18** [ArcadeTV/msu-md-shinobi2#4]
**Patch version**
0.2

**Platform**
Genesis VA3 with MegaSD

**Describe the bug**
1 - Invencibilty
2 - Opening music theme don't stop after you press start and keep playing in the options menu and in the map round presentation
3 - When you pause the game, if the music ends it doesn't loop, it goes to the next music stage

**Additional context**
By the way thanks so much for the hardwork :)

**Comment by ArcadeTV** [comment]
Thanks for the feedback!

1. I will provide 2 patches in v1.0: with and without cheat
2. I'm working on this right now, see "known issues".
3. That sounds like a typical MegaSD behaviour which has been reported for other games too. I don't have a MegaSD and this will probably be fixed in their next firmware, so there's not much I can do about it. The music also keeps playing in the original game, so I didn't implement a pause-music here.

**Comment by ArcadeTV** [comment]
fixed in v1.0 (thanks to PepilloPEV and neodev)
